# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: 		"" # the subpath of your site, e.g. /blog
url:			"http://blog.christophe-hermann.fr" # the base hostname & protocol for your site
paginate:		5
paginate_path:	"/page-:num/"


# Permalinks
permalink:           :year/:month/:title.html


# Build settings
markdown: kramdown


# Plugins
gems:
  - jekyll-assets
  - jekyll-paginate


# About/contact
title:               Au Front - Blog d'un intégrateur et designer front-end
description:         "HTML, CSS, JS"
author:
  name:              Christophe Hermann
  url:               http://www.christophe-hermann.fr
  email:             contact@christophe-hermann.fr
  twitter_username:  chrishrmnn
  github_username:   chrishrmnn


# Assets
assets:
  js_compressor: 	uglifier
  css_compressor: 	sass
  cache: 			_cache/